# Netlify configuration file

[build]
# Directory to publish (make sure this matches the 'site_dir' in your mkdocs.yml)
publish = "site"

# The command to build your site
command = """
pip install uv &&
uv sync --frozen &&
uv run mkdocs build --clean
"""

[build.environment]
# Specify the Python version to use
PYTHON_VERSION = "3.11"